// This file was auto-generated by cpptoswift.
// Do not edit this file, edit the original source file /Users/uli/Programming/intercombatsystem/intercombatsystem_cpp/intercombatsystem_number.h

public class intercombatsystem
{
	let cppinstance : COpaquePointer

	deinit {
		intercombatsystem_deinit(cppinstance)
	}

	public init() {
		cppinstance = intercombatsystem_init()
	}

	public func method(theNum : Int32) -> Void {
		return intercombatsystem_method(cppinstance, theNum)
	}

}
