// This file was auto-generated by cpptoswift.
// Do not edit this file, edit the original source file /Users/uli/Programming/intercombatsystem/intercombatsystem_cpp/intercombatsystem_number.h

#include "/Users/uli/Programming/intercombatsystem/intercombatsystem_cpp/intercombatsystem.h"
#include "/Users/uli/Programming/intercombatsystem/intercombatsystem_cpp/intercombatsystem_number.h"


extern "C" void intercombatsystem_deinit( intercombatsystem* _this )
{
	delete _this;
}

extern "C" intercombatsystem* intercombatsystem_init( void )
{
	return new intercombatsystem;
}

extern "C" void intercombatsystem_method( intercombatsystem* _this,  int theNum )
{
	return _this->method(theNum);
}

