// This file was auto-generated by cpptoswift.
// Do not edit this file, edit the original source file /Users/uli/Programming/intercombatsystem/intercombatsystem_cpp/intercombatsystem_cpp.hpp

public class intercombatactor
{
	let cppinstance : COpaquePointer

	deinit {
		intercombatactor_deinit(cppinstance)
	}

	public init() {
		cppinstance = intercombatactor_init()
	}

	public func turn_by_radians(radians : Double) -> Void {
		return intercombatactor_turn_by_radians(cppinstance, radians)
	}

	public func radian_angle_to_actor(target : intercombatactor) -> Double {
		return intercombatactor_radian_angle_to_actor(cppinstance, target.cppinstance)
	}

	public func distance_to_actor(target : intercombatactor) -> Double {
		return intercombatactor_distance_to_actor(cppinstance, target.cppinstance)
	}

	public func get_angle() -> Double {
		return intercombatactor_get_angle(cppinstance)
	}

	public func get_x() -> Double {
		return intercombatactor_get_x(cppinstance)
	}

	public func set_x(inX : Double) -> Void {
		return intercombatactor_set_x(cppinstance, inX)
	}

	public func get_y() -> Double {
		return intercombatactor_get_y(cppinstance)
	}

	public func set_y(inY : Double) -> Void {
		return intercombatactor_set_y(cppinstance, inY)
	}

}
