// This file was auto-generated by cpptoswift.
// Do not edit this file, edit the original source file /Users/uli/Programming/intercombatsystem/intercombatsystem_cpp/intercombatsystem.hpp

#include "intercombatsystem_cp2s.h"
#include "intercombatsystem.hpp"


extern "C" void intercombatactor_deinit( intercombatactor* _this )
{
	delete _this;
}

extern "C" intercombatactor* intercombatactor_init( void )
{
	return new intercombatactor;
}

extern "C" void intercombatactor_turn_by_radians( intercombatactor* _this,  double radians )
{
	return _this->turn_by_radians(radians);
}

extern "C" double intercombatactor_radian_angle_to_actor( intercombatactor* _this,  intercombatactor* target )
{
	return _this->radian_angle_to_actor(target);
}

extern "C" double intercombatactor_distance_to_actor( intercombatactor* _this,  intercombatactor* target )
{
	return _this->distance_to_actor(target);
}

extern "C" double intercombatactor_get_angle( intercombatactor* _this )
{
	return _this->get_angle();
}

extern "C" double intercombatactor_get_x( intercombatactor* _this )
{
	return _this->get_x();
}

extern "C" void intercombatactor_set_x( intercombatactor* _this,  double inX )
{
	return _this->set_x(inX);
}

extern "C" double intercombatactor_get_y( intercombatactor* _this )
{
	return _this->get_y();
}

extern "C" void intercombatactor_set_y( intercombatactor* _this,  double inY )
{
	return _this->set_y(inY);
}

