// This file was auto-generated by cpptoswift.
// Do not edit this file, edit the original source file /Users/uli/Programming/intercombatsystem/intercombatsystem_cpp/intercombatsystem_number.h

#if __cplusplus
extern "C"
{
#endif /* __cplusplus */

typedef struct intercombatsystem intercombatsystem;

void intercombatsystem_deinit( intercombatsystem* _this );
intercombatsystem* intercombatsystem_init( void );
void intercombatsystem_method( intercombatsystem* _this,  int theNum );

#if __cplusplus
}
#endif /* __cplusplus */
